### ISSUE TITLE
Convert to Aptos Move V2

### ISSUE THREAD

**Issue by huisq** [Art3misOracle/contracts#1]
convert to aptos move v2 while keeping the existing functionality

**Comment by Nityam573** [comment]
Mind if I take this issue?

**Comment by Fajjf** [comment]
Hello @huisq  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by estherbreath** [comment]
Can I work on this, please?

To convert the existing contracts to Aptos Move v2 while maintaining functionality, I would;
    1. Analyze the current contract structure and identify key components. 
    2. Rewrite the contracts using Aptos Move v2 syntax and semantics. 
    3. Ensure all existing functionality is preserved in the new implementation, focusing on compatibility with Aptos Move v2 features and constraints.
     
ETA: 2-3 days

**Comment by SoarinSkySagar** [comment]
may i work on this @huisq?

this will be my first time writing contracts in mocve but i have experience in writing smart contracts with similar syntax (rust and cairo) so i can get it done

eta: 3 days

**Comment by ryzen-xp** [comment]
Hi,
 I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects etc.
I can efficiently convert the code to Aptos Move V2 while ensuring the existing functionality remains intact. Please assign this issue to me.

Thank you!

**Comment by mimisavage** [comment]
I'd be happy to do this.

**Comment by Ndifreke000** [comment]
Can I contribute to this one?

**Comment by GideonBature** [comment]
Would love to tackle this!

My name is Gideon Bature, a Software Engineer, I have experience with Aptos Move and have built and deployed to the Aptos Devnet. I will like to contribute to this project as I have been longing to contribute to an Aptos open source project. If given the opportunity, I will send my first PR within 72 hours.

Thank you!

**Comment by Supa-mega** [comment]
Is this issue still available?

**Comment by trashcancries** [comment]
may i work on this @huisq?


eta: 3 days

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by od-hunter** [comment]
Can I be assigned this please? Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

Kindly assign me please, I'm available to work.

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by caxtonacollins** [comment]
Can I handle this task?

**Comment by DuendexCR** [comment]
I’d like to help with this.

**Comment by GideonBature** [comment]
Thank you @huisq I will start working on this as soon as possible.

**Comment by GideonBature** [comment]
@huisq GM. There is a variable `MAJOR_ARCANA_CARD_URI` that is used in the code, on line `394` but is not declared, please can you provide the variable? so that I can start testing...

**Comment by huisq** [comment]
> @huisq GM. There is a variable `MAJOR_ARCANA_CARD_URI` that is used in the code, on line `394` but is not declared, please can you provide the variable? so that I can start testing...

it is deprecated.
